run:
  deadline: 5m

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck