name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Run tests
        run: go test -v ./...

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o screenshot-sorter-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o screenshot-sorter-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o screenshot-sorter-darwin-amd64

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            screenshot-sorter-linux-amd64
            screenshot-sorter-windows-amd64.exe
            screenshot-sorter-darwin-amd64
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}